site_name: 'Meu Serviço API'
nav:
  - 'Visão Geral': 'index.md'
  - 'Guias':
    - 'Configuração Inicial': 'guides/01-configuracao.md'
    - 'Solução de Problemas': 'guides/02-troubleshooting.md'
  - 'Referência da API':
    - 'Endpoints': 'api/endpoints.md'
